### PR TITLE
Add Heiko's video

### PR DESCRIPTION
**Pull request by theute**
Unfortunately we can't directly embed the video with Markdown...

### CODE REVIEW

**Comment by pilhuhn** [comment]
What about putting a "caption" below the screenshot saying "click for an intro video" ?

**Comment by theute** [comment]
Or a trick to invite clicking is to change the picture with a screenshot of the video player like this:
kiali_video

**Comment by pilhuhn** [comment]
@theute sounds good

**Comment by theute** [comment]
I'm merging, as a first step anyway...

**Pull request merged**
