### PR TITLE
KIALI-1012 Integrate Swagger documentation on the website

### PR DESCRIPTION
**Pull request by aljesusg**
This is a improvement of navegation in the website.
I am still working but I wanna feedback about.

- [X] Added Api Docs documentation
- [X] Structured Documentation
- [X] Layouts, this lets us make template
- [X] Let make our own header and footer
- [X] Pages directory
- [X] Navigation control with a Yaml

- [X] Added Documentation generated by Swagger

Now if we merge https://github.com/kiali/kiali/pull/281 after generate the swagger.json file with :
```bash
 make swagger-gen swagger.validate
```

Added Script to generate docs from swagger.json allocated in kiali/kiali so we only need execute here a travis to generate this docs and add them to the repo.

Travis sample
```yaml
lang: ruby
script:
  - make swagger-doc
after_success:
  - ./scripts/push_api_docs.sh
env:
  global:
  secure: hZJlqgOzA2zIUJSWIka0PylqNaTkfHq+kS48RrHmocrK0vLyCW7ECWrzez2f2RVdTNzPi0b+yJq2uCbFfWjImZqg+XY1I75/CVVdSYMk7PJkYZ/iBDixMYY8CAkRRd5yZft9uZAdZzR4KLCPN18n7qfISv/M9VA8989NKcVyiEU=
```
/scripts/push_api_docs.sh
```bash
#!/bin/sh

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name  "Travis CI"
}

commit_swagger_doc_files() {
  git add pages/api/*
  git commit --message "Travis build: $TRAVIS_BUILD_NUMBER . Generate Api Docs"
}

upload_files() {
  git remote add origin https://${GH_TOKEN}@github.com/kiali/kiali.github.io.git > /dev/null 2>&1
  git push --quiet --set-upstream origin master
}

setup_git
commit_swagger_doc_files
upload_files
```
cc @theute @pilhuhn 
We can add the patternfly style now and work in some templates and keep the markdown files 
Here is the Live Demo : [https://aljesusg.github.io/kiali.github.io/](https://aljesusg.github.io/kiali.github.io/)

### CODE REVIEW

**Comment by pilhuhn** [comment]
On 22 Jun 2018, at 14:25, Alberto Gutierrez wrote:

> Here is the Live Demo : 
> [https://aljesusg.github.io/kiali.github.io/](https://aljesusg.github.io/kiali.github.io/)
> You can view, comment on, or merge this pull request online

Cool. Would it be possible to show the api doc in the lower part like in 
an iFrame?
Not sure if this is a good idea though.
I guess the swaggerhub page can't be customised to more look like 
kiali.io?

**Comment by aljesusg** [comment]
I am working now in have some style similar to patternfly with the same css, in parallel I have a script to convert the swagger documentation to markdown https://github.com/kiali/kiali/pull/281 so we can push the result to this site with travis and have all the code in the same place, the swaggerhub link is a temporal site while I finish this

**Comment by aljesusg** [comment]
Ok @pilhuhn @theute Check now the website ^^
[https://aljesusg.github.io/kiali.github.io/](https://aljesusg.github.io/kiali.github.io/)

**Comment by pilhuhn** [comment]
If the screen is too narrow, the navigation links are not shown.

**Comment by aljesusg** [comment]
I know, I check it on the mobile I need to set the code for small screens ^^

**Comment by aljesusg** [comment]
Ok you can check now @pilhuhn ^^

**Comment by pilhuhn** [comment]
Better 😀
Not sure if the nav should start open though

Am 23. Juni 2018 21:35:55 schrieb Alberto Gutierrez <notifications@github.com>:

**Comment by aljesusg** [comment]
Fixed @pilhuhn, now working in the swagger integration

**Comment by aljesusg** [comment]
Ok now we can integrate the documentation generated in swagger in kiali/kiali I am going to work now in improve this docs

**Comment by aljesusg** [comment]
Improved css Style like PF in tables of API doc generated

## Before 
before_pf_css

## After PF Style

after_pf_css


See Live Demo: [Demo](https://aljesusg.github.io/kiali.github.io)

**Comment by theute** [comment]
I'm good with that, the link to GitHub is less obvious though, @pilhuhn do you think we should address that before we merge ?

**Comment by pilhuhn** [comment]
@theute I think this is good. The link to GitHub is also in the text of the start page.
We could add one of those "fork me on GitHub" ribbons, but I am not sure if the cool kids still do that in 2018 :)

**Comment by aljesusg** [comment]
I removed the link to github about fork I can add it again.

**Pull request merged**
